### ISSUE TITLE
Error on Raspberry Pi

### ISSUE THREAD

**Issue by spotter-ssol** [spottair-com/AlertAir#1]
When trying to run raspbian buster:
`sed: -e expression #1, char 20: Invalid range end`

**Comment by spaceserver** [comment]
got the same on archlinux & couldnt debug it.. is there nothing to be done about it? kinda seems to be shell-syntax related but it neither runs on bash nor on sh ..
guess i'll never get some plane notifications..

**Comment by spaceserver** [comment]
puh.. i somehow managed to fix it..
the list-section has to look like this:

aircraft_list="'"
aircraft_list+=$(sed '/^#/d' $aircraft_file |
		 sed 's/#.*//g' | 
		 sed ':a;N;$!ba;s/\n/\x27,\x27/g')
aircraft_list+="'"


can therefore be marked as solved..

**Comment by spotter-ssol** [comment]
Great! Thanks!
